{\rtf1\ansi\ansicpg1252\cocoartf1404\cocoasubrtf460
{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
\margl1440\margr1440\vieww25400\viewh13680\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 version: 0.1\
\
phases:\
  install:\
    commands:\
      - echo Nothing to do in the install phase...\
  pre_build:\
    commands:\
      - echo Nothing to do in the pre_build phase...\
  build:\
    commands:\
      - mvn install\
  post_build:\
    commands:\

artifacts:\
  files:\
    - target/messageUtil-1.0.jar}